const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: { width: 375, height: 667 }, // mobile viewport like user's screenshot
    deviceScaleFactor: 2,
    isMobile: true
  });
  const page = await context.newPage();

  page.on('console', msg => console.log('PAGE LOG:', msg.text()));

  // Need to mock fetchRandomAyahData since it makes alquran.cloud requests that take time and could fail

  // Load the page
  await page.goto('http://localhost:8080');

  // Dismiss setup modal if it appears
  try {
    await page.waitForSelector('#welcome-setup-btn', { timeout: 2000 });
    await page.click('#welcome-setup-btn');
    await page.waitForSelector('#close-settings-modal', { timeout: 2000 });
    await page.click('#close-settings-modal');
  } catch (e) {
    console.log("No welcome modal.");
  }

  // Intercept and mock API requests to simulate Gemini failing and Groq succeeding
  await page.route('https://generativelanguage.googleapis.com/**', async route => {
    // Fail Gemini
    console.log("Mocking Gemini failure");
    await route.fulfill({
        status: 400,
        body: '{"error": "Simulated Gemini Failure"}'
    });
  });

  await page.route('https://api.groq.com/**', async route => {
    // Succeed Groq
    console.log("Mocking Groq success");
    await route.fulfill({
        status: 200,
        body: JSON.stringify({
            choices: [{
                message: {
                    content: JSON.stringify({
                        ayahContext: "Mock Ayah Text",
                        ayahTranslation: "Mock Ayah Translation",
                        surahRef: "Mock Surah 1:1",
                        question: "Mock Question generated by Groq?",
                        options: {
                            A: "Option A",
                            B: "Option B",
                            C: "Option C",
                            D: "Option D"
                        },
                        answer: "A",
                        explanation: "Mock Explanation"
                    })
                }
            }]
        })
    });
  });

  // Inject keys directly via page evaluation since it's cleaner than guessing UI selectors
  await page.evaluate(async () => {
     // Force global variables
     apiKeys = ["mock_gemini_key"];
     groqApiKeys = ["mock_groq_key"];

     // Also inject fetchRandomAyahData mock
     window.fetchRandomAyahData = async () => {
         return {
            surahNum: 1,
            surahName: "Mock Surah",
            ayahNum: 1,
            text: "Mock Ayah Text",
            translation: "Mock Ayah Translation"
         };
     };
  });

  // Navigate to Quiz section
  await page.click('#quiz-nav-btn');

  // Wait for it to be visible
  await page.waitForSelector('#quiz-setup-view', { state: 'visible' });

  // Start the quiz
  await page.click('#start-quiz-btn');

  // Wait for the question to render
  try {
    await page.waitForSelector('#quiz-question-container', { state: 'visible', timeout: 5000 });
    console.log("Quiz question rendered successfully.");
  } catch (e) {
    console.log("Quiz failed to render.");
  }

  // Take screenshot
  await page.screenshot({ path: 'quiz_groq_fallback_check.png' });

  await browser.close();
})();
